data types -4

In [ ]:
inte = 20
stri = "hel"
floa = 20.13
boole = False

list

In [ ]:
l = ["1","2","3","4","5"]
print(l[0],l[4])

list problem

In [ ]:
l=[1,2,3,4]
for i in l:
  if(i>40):
    print("Pass")
  else:
    print("Fail")





Fail
Fail
Fail
Fail


list problem 2

In [ ]:
l=[0,-1,5,100]
for i in l:
  if(i==0):
    print("zero")
  elif(i>0):
    print("+ve")
  else:
    print("-ve")

dictionary problem 1

In [ ]:
d = {
    "a":[5,71,60],
    "b":[6,66,76],
    "c":[1,81,97],
    "d":[8,99,87],
    "e":[7,90,92]
}
name = input()
if(d[name][2]>75):
  print("strong perfomance")
elif(d[name][2]>=40):
  print("need improvement")
else:
  print("repeat class")

if(d[name][1]<75):
  print("warning-low attendance")

if(d[name][0]<2):
  print("warning-study more")




c
strong perfomance
warning-study more


dictionary problem 2

In [ ]:
# Student Starter Code
transactions = [
    {"transaction_id": "TX101", "amount": 6200, "method": "Credit Card"},
    {"transaction_id": "TX102", "amount": 5500, "method": "Gift Card"},
    {"transaction_id": "TX103", "amount": 1200, "method": "Gift Card"},
    {"transaction_id": "TX104", "amount": 8000, "method": "Gift Card"},
    {"transaction_id": "TX105", "amount": 450, "method": "PayPal"}
]

flagged_transactions = []

# Write your code below to find anomalous patterns|


for i in range(len(transactions)):
  if(transactions[i]["amount"]>5000 and transactions[i]["method"]=="Gift Card"):
    flagged_transactions.append(transactions[i]["transaction_id"])

for i in flagged_transactions:
  print(i)


TX102
TX104


dictionary problem 2 alternate solution


In [ ]:
#Student Starter Code
transactions = [
    {"transaction_id": "TX101", "amount": 6200, "method": "Credit Card"},
    {"transaction_id": "TX102", "amount": 5500, "method": "Gift Card"},
    {"transaction_id": "TX103", "amount": 1200, "method": "Gift Card"},
    {"transaction_id": "TX104", "amount": 8000, "method": "Gift Card"},
    {"transaction_id": "TX105", "amount": 450, "method": "PayPal"}
]

flagged_transactions = []

# Write your code below to find anomalous patterns|


for i in transactions:
  if(i["amount"]>5000 and i["method"]=="Gift Card"):
    flagged_transactions.append(i["transaction_id"])

for i in flagged_transactions:
  print(i)

TX102
TX104


week 2 session 2

reusable function for pass fail condition checking.

In [ ]:
def pass_fail(marks):
  if(marks>27):
    print("pass")
  else:
    print("fail")
pass_fail(58)

pass


shape = structure of array
index = position of each element
axis  =  direction of calculation across rows and columns or xyz axis


In [ ]:
import numpy as np
#shape, airthemtic operation

a = np.array([1,2,3])
print(a+10)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b,b.shape)

#slicing 1d,2d,3d - array[1d start: end, 2d start:end, 3d start:end]

c = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(c[0,0])
print(c[0,])
print(c[1][2])
print(c[:,0])
print(c[0:3,0:3])


#a.sum(),a.mean(),a.max(),a.min()

#filtering
l1 = np.array([78, 91, 55, 72, 40, 88,98,81,11,23,78,88,91,96])
cnt = l1[l1>75]



[11 12 13]
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
1
[1 2 3 4]
7
[ 1  5  9 13]


In [ ]:
import numpy as np
l = np.array([78, 91, 55, 72, 40, 88,98,81,11,23,78,88,91,96])
print(l.max(),l.min(),len(l[l>75]))


98 11 9


In [ ]:
from google.colab import files
uploaded =files.upload()

Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv.xls


In [ ]:
#s_s=df["science"].to_numpy()

In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv.xls")
print(df)
print(df.head())
print(df.info())
print(df.columns)

df["average"] = df[["math", "science", "english"]].mean(axis=1)
print(df[["name", "math", "science", "english", "average"]])





    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

filtering other subject


In [ ]:
low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

mathura_stu=df[df["city"]=="Mathura"]
print(mathura_stu[["name","city","average"]])


      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66
      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000


In [ ]:

def f(n):
  if(n<40):
    return "Pass"
  else:
    return "Fail"




cf = pd.read_csv("session4_dummy_students_data.csv.xls")
cf["avg"]=cf[["math","science","english"]].mean(axis=1)

cf["result"]=cf["avg"].apply(f)

print(cf["avg"].mean())
print(cf["avg"].max())
print(cf["avg"].min())

low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

mathura_stu=df[df["city"]=="Mathura"]
print(mathura_stu[["name","city","average"]])

stud = cf[cf["assignments_submitted"]<6]
print(stud[["name"]])

71.35000000000001
92.66666666666667
40.666666666666664
      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66
      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000
     name
4   Rohan
12    Dev
18   Yash
